exploit
JohnTwiiX/dso-python-tasks pull request #7
Opened 2024-07-08 07:59 UTC by JohnTwiiX

# Description
Add the exploit example CMD line program and a little documentation about this file in README.md.

2024-07-16 19:24 UTC, spmse requested changes
Hello John! I left a small review for your PR.

It looks very good from documentation and code side, but there are some small adjustments, or improvements that would make the code even better.

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/.gitignore
> +/keepass-dump-masterkey/
in the best case you can create your gitignore file on a website like https://gitignore.io in order to not miss any things that should be ignored in git repositories.

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/README.md
> +  - Ensure that the password dumper script or tool is working correctly and accessible in the specified directory.
what is criteria that i can check to ensure everything is configured correctly? point out what you expect from a potential user in that place

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/README.md
> +Main function that coordinates the reading of `.kdbx` and `.DMP` files, generating passwords, and attempting to log in.
since you have a very good documented code down there you may delete this section in the readme :)

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +    except subprocess.CalledProcessError as e:
import `run`, `CalledProcessError` (and other functions you might use) from the subprocess module directly

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +        print(f'KDBX files founded:\n{kdbx_files}')
```suggestion
        print(f'DUMP files found:\n{dmp_files},\n')
        print(f'KDBX files found:\n{kdbx_files}')
```

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +                    exit()
this is somewhat of an error case right? So you should raise an Error here or at least exit the program with a non zero exit code. You could either raise a basic Error with a custom message to make sure the user will have a good feedback on why the program failed, or alternatively write your own class that inherits from the Exception class and raise an error of that type. The choice is yours 

Non-Zero exit codes are a way to signal the unsuccessful completion of a program execution.

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +                    print('Reading DUMP file successfully!')
Since you're practically done with reading the file maybe change your output to "Read DUMP file successfully".
Alternatively, put that line before you actually try to read the file and remove the word "sucessfully" from the print

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +            print(f'Founded passwords:\n{successfully_passwords}')
grammar: "found"

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +            print('No correct password pair founded.')
"found"

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +        return passwords
no need for another variable, simply return result

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +                        passwords_to_try = generate_passwords(start_char, [password_tail])
add a comment why you do that (the slicing) here.
also the name password_tail indicates that it is everything of the password string except the first character, or depending on your interpretation of tail only the last N character(s), but actually your password tail is from the 20th character to the end (so your password needs to fulfill that criteria in each and every case).
also you pass it a single-element list into the function generate_passwords, which is actually not needed since you also could only pass in a single value and you would save another iterator in the other function (not too important, but as far as i can recognize, this is the only usage of that function)

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +            print('Passwords were written to the file .potfile.')
you can also add one identation here to make this print more related with the `with open()` construct above, which would be the correct location (in terms of code-logic/-splitting)

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +        print('\nYou exit the program manually.')
"exited"

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +    exit()
remove, since the last print from `main` should be sufficint in that place. The exit call is unnecessary in that place, since the program would stop its execution without raising an error (<=> exit 0).

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +def read_dump_file(dmp_file: str, keepass_dump_dir:str="./keepass-dump-masterkey"):
add return value hint

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +def generate_passwords(start_char:str, password_parts: List[str]):
add return value hint

2024-07-16 19:24 UTC, spmse commented on module-4/exploit/exploit.py
> +def try_login(kdbx_file:str, password:str):
add return value hint

2024-07-16 19:38 UTC, spmse requested changes
Hi John! I left a small review for you :)

2024-07-17 11:41 UTC, JohnTwiiX commented on module-4/exploit/.gitignore
> +/keepass-dump-masterkey/
i worked without env. i would like ignore only this directories :D

2024-09-15 12:09 UTC, merged